# Generated by Django 6.0.4 on 2026-04-15 17:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDocument',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, unique=True)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('confidentiality', models.CharField(choices=[('UNCLASSIFIED', 'Không phân loại'), ('CONFIDENTIAL', 'Mật'), ('SECRET', 'Tuyệt mật'), ('TOP_SECRET', 'Tối mật')], default='UNCLASSIFIED', max_length=20)),
                ('department', models.CharField(choices=[('ADMIN', 'Phòng Quản lý Hành chính'), ('PLANNING', 'Phòng Kế hoạch Tài chính'), ('ENVIRONMENT', 'Phòng Tài nguyên Môi trường'), ('GENERAL', 'Phòng Tổng hợp'), ('HUMAN_RESOURCES', 'Phòng Tổ chức Cán bộ'), ('MANAGEMENT', 'Ban Giám đốc'), ('CLERK', 'Văn thư')], default='GENERAL', max_length=50)),
                ('document_type', models.CharField(choices=[('OFFICIAL_LETTER', 'Công văn'), ('REPORT', 'Báo cáo'), ('DECISION', 'Quyết định'), ('OTHER', 'Khác')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Mới'), ('IN_PROGRESS', 'Đang xử lý'), ('PENDING_COORDINATION', 'Chờ phối hợp'), ('PENDING_APPROVAL', 'Chờ phê duyệt'), ('OVERDUE', 'Quá hạn'), ('COMPLETED', 'Hoàn tất')], default='NEW', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowDocumentAttachment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='workflow_documents/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.workflowdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
