# Generated by Django 6.0.4 on 2026-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocumentattachment',
            name='upload_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
