# Generated by Django 6.0.4 on 2026-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_workflowdocumentattachment_upload_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdocument',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
