# Generated by Django 6.0.4 on 2026-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_workflowdocument_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowdocument',
            name='document_type',
            field=models.CharField(choices=[('OFFICIAL_LETTER', 'Công văn'), ('REPORT', 'Báo cáo'), ('DECISION', 'Quyết định'), ('DOCUMENT', 'Văn bản'), ('FORM', 'Phiếu trình'), ('ANNOUNCEMENT', 'Thông báo'), ('OTHER', 'Khác')], default='OTHER', max_length=20),
        ),
    ]
