# Generated by Django 6.0.4 on 2026-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_workflowdocument_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocument',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='related_docs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='suggested_dept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowdocument',
            name='suggested_reviewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
