# Generated by Django 6.0.4 on 2026-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_workflowdocument_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdocumentattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
