# Generated by Django 6.0.4 on 2026-04-17 14:49

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_workflowdocumentattachment_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDocumentAIDraftResponse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_draft_response', to='documents.workflowdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
