# Generated by Django 6.0.4 on 2026-04-15 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='orgs.agency')),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('handles_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='orgs.agency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='orgs.department')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['is_active', 'name'], name='orgs_agency_is_acti_4a1521_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['parent'], name='orgs_agency_parent__e8ec6b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['agency', 'is_active'], name='orgs_depart_agency__7892c2_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='orgs_depart_parent__0a1d74_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['sort_order', 'name'], name='orgs_depart_sort_or_e87124_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('agency', 'code'), name='uniq_department_code_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='uniq_department_name_per_agency'),
        ),
    ]
