# Generated by Django 6.0.4 on 2026-04-17 02:35

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stage', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('ADMIN', 'Phòng Quản lý Hành chính'), ('PLANNING', 'Phòng Kế hoạch Tài chính'), ('ENVIRONMENT', 'Phòng Tài nguyên Môi trường'), ('GENERAL', 'Phòng Tổng hợp'), ('HUMAN_RESOURCES', 'Phòng Tổ chức Cán bộ'), ('MANAGEMENT', 'Ban Giám đốc'), ('CLERK', 'Văn thư')], max_length=50)),
                ('assignee', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('pending', 'Pending')], max_length=20)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
