# Generated by Django 6.0.4 on 2026-04-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_workflowdocument_entities_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='documents.workflowdocument'),
        ),
    ]
