# Generated by Django 6.0.4 on 2026-04-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstep_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='stage',
            field=models.CharField(choices=[('Tiếp nhận', 'Intake'), ('Phân loại & Đăng ký', 'Classification And Registration'), ('Phân phối', 'Distribution'), ('Xử lý chuyên môn', 'Specialized Processing'), ('Phê duyệt', 'Approval'), ('Phát hành phản hồi', 'Feedback Distribution')], default='Tiếp nhận', max_length=255),
        ),
    ]
