/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description class used for social authentications
         *     example usage for facebook with access_token
         *     -------------
         *     from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
         *
         *     class FacebookLogin(SocialLoginView):
         *         adapter_class = FacebookOAuth2Adapter
         *     -------------
         *
         *     example usage for facebook with code
         *
         *     -------------
         *     from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
         *     from allauth.socialaccount.providers.oauth2.client import OAuth2Client
         *
         *     class FacebookLogin(SocialLoginView):
         *         adapter_class = FacebookOAuth2Adapter
         *         client_class = OAuth2Client
         *         callback_url = 'localhost:8000'
         *     -------------
         */
        post: operations["auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Check the credentials and return the REST Token
         *     if the credentials are valid and authenticated.
         *     Calls Django Auth login method to register User ID
         *     in Django session framework
         *
         *     Accept the following POST parameters: username, password
         *     Return the REST Framework Token Object's key.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django logout method and delete the Token object
         *     assigned to the current User object.
         *
         *     Accepts/Returns nothing.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth SetPasswordForm save method.
         *
         *     Accepts the following POST parameters: new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth PasswordResetForm save method.
         *
         *     Accepts the following POST parameters: email
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Password reset e-mail link is confirmed, therefore
         *     this resets the user's password.
         *
         *     Accepts the following POST parameters: token, uid,
         *         new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        get: operations["auth_user_retrieve"];
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        put: operations["auth_user_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        patch: operations["auth_user_partial_update"];
        trace?: never;
    };
    "/api/chats/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to list all conversations for the authenticated user. */
        get: operations["chats_conversations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/conversations/{conversation_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description API view to handle chat interactions within a conversation. */
        post: operations["chats_conversations_chat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/conversations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to retrieve details of a specific conversation, including its messages. */
        get: operations["chats_conversations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/conversations/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description API view to create a new conversation for the authenticated user. */
        post: operations["chats_conversations_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/conversations/last-7-days/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to list conversations from the last 7 days for the authenticated user. */
        get: operations["chats_conversations_last_7_days_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/conversations/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view to list conversations from today for the authenticated user. */
        get: operations["chats_conversations_today_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["documents_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/agencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_agencies_list"];
        put?: never;
        post: operations["orgs_agencies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/agencies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_agencies_retrieve"];
        put: operations["orgs_agencies_update"];
        post?: never;
        delete: operations["orgs_agencies_destroy"];
        options?: never;
        head?: never;
        patch: operations["orgs_agencies_partial_update"];
        trace?: never;
    };
    "/api/orgs/agencies/{id}/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_agencies_departments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_departments_list"];
        put?: never;
        post: operations["orgs_departments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_departments_retrieve"];
        put: operations["orgs_departments_update"];
        post?: never;
        delete: operations["orgs_departments_destroy"];
        options?: never;
        head?: never;
        patch: operations["orgs_departments_partial_update"];
        trace?: never;
    };
    "/api/orgs/departments/tree/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_departments_tree_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put: operations["users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/document/{document_id}/workflow-steps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workflows_document_workflow_steps_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/workflow-steps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workflows_workflow_steps_list"];
        put?: never;
        post: operations["workflows_workflow_steps_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/workflow-steps/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workflows_workflow_steps_retrieve"];
        put: operations["workflows_workflow_steps_update"];
        post?: never;
        delete: operations["workflows_workflow_steps_destroy"];
        options?: never;
        head?: never;
        patch: operations["workflows_workflow_steps_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agency: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            name: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            readonly parent_name: string;
            is_active?: boolean;
            readonly children_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AgencyRequest: {
            code: string;
            name: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            is_active?: boolean;
        };
        AuthToken: {
            readonly token: string;
        };
        AuthTokenRequest: {
            username: string;
            password: string;
        };
        /**
         * @description * `UNCLASSIFIED` - Không phân loại
         *     * `CONFIDENTIAL` - Mật
         *     * `SECRET` - Tuyệt mật
         *     * `TOP_SECRET` - Tối mật
         * @enum {string}
         */
        ConfidentialityEnum: "UNCLASSIFIED" | "CONFIDENTIAL" | "SECRET" | "TOP_SECRET";
        Conversation: {
            /** Format: uuid */
            readonly id: string;
            readonly user: number;
            title?: string;
            system_prompt?: string;
            /** Format: date-time */
            readonly last_message_at: string | null;
        };
        ConversationCreate: {
            /** Format: uuid */
            readonly id: string;
            title?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ConversationCreateRequest: {
            title?: string;
        };
        ConversationDetailResponse: {
            conversation: components["schemas"]["Conversation"];
            messages: components["schemas"]["Message"][];
        };
        Department: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            agency: string;
            readonly agency_name: string;
            code: string;
            name: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            readonly parent_name: string;
            sort_order?: number;
            is_active?: boolean;
            handles_confidential?: boolean;
            readonly children_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `ADMIN` - Phòng Quản lý Hành chính
         *     * `PLANNING` - Phòng Kế hoạch Tài chính
         *     * `ENVIRONMENT` - Phòng Tài nguyên Môi trường
         *     * `GENERAL` - Phòng Tổng hợp
         *     * `HUMAN_RESOURCES` - Phòng Tổ chức Cán bộ
         *     * `MANAGEMENT` - Ban Giám đốc
         *     * `CLERK` - Văn thư
         * @enum {string}
         */
        DepartmentEnum: "ADMIN" | "PLANNING" | "ENVIRONMENT" | "GENERAL" | "HUMAN_RESOURCES" | "MANAGEMENT" | "CLERK";
        DepartmentRequest: {
            /** Format: uuid */
            agency: string;
            code: string;
            name: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            sort_order?: number;
            is_active?: boolean;
            handles_confidential?: boolean;
        };
        /**
         * @description * `OFFICIAL_LETTER` - Công văn
         *     * `REPORT` - Báo cáo
         *     * `DECISION` - Quyết định
         *     * `DOCUMENT` - Văn bản
         *     * `FORM` - Phiếu trình
         *     * `ANNOUNCEMENT` - Thông báo
         *     * `OTHER` - Khác
         * @enum {string}
         */
        DocumentTypeEnum: "OFFICIAL_LETTER" | "REPORT" | "DECISION" | "DOCUMENT" | "FORM" | "ANNOUNCEMENT" | "OTHER";
        /** @description Serializer for JWT authentication. */
        JWT: {
            access: string;
            refresh: string;
            user: components["schemas"]["UserDetails"];
        };
        LoginRequest: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        Message: {
            readonly id: number;
            /** Format: uuid */
            readonly conversation: string;
            role: components["schemas"]["RoleEnum"];
            content: string;
            readonly order: number;
            readonly status: components["schemas"]["MessageStatusEnum"];
            readonly error_message: string;
        };
        MessageChatRequest: {
            content: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        MessageStatusEnum: "pending" | "completed" | "failed";
        PaginatedAgencyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Agency"][];
        };
        PaginatedConversationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Conversation"][];
        };
        PaginatedDepartmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Department"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        PaginatedWorkflowDocumentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkflowDocument"][];
        };
        PaginatedWorkflowStepList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkflowStep"][];
        };
        PasswordChangeRequest: {
            new_password1: string;
            new_password2: string;
        };
        /** @description Serializer for confirming a password reset attempt. */
        PasswordResetConfirmRequest: {
            new_password1: string;
            new_password2: string;
            uid: string;
            token: string;
        };
        /** @description Serializer for requesting a password reset e-mail. */
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PatchedAgencyRequest: {
            code?: string;
            name?: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            is_active?: boolean;
        };
        PatchedDepartmentRequest: {
            /** Format: uuid */
            agency?: string;
            code?: string;
            name?: string;
            short_name?: string;
            /** Format: uuid */
            parent?: string | null;
            sort_order?: number;
            is_active?: boolean;
            handles_confidential?: boolean;
        };
        /** @description User model w/o password */
        PatchedUserDetailsRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
        };
        PatchedUserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            /** Name of User */
            name?: string;
        };
        PatchedWorkflowStepRequest: {
            stage?: components["schemas"]["StageEnum"];
            department?: components["schemas"]["DepartmentEnum"];
            assignee?: string;
            status?: components["schemas"]["WorkflowStepStatusEnum"];
            /** Format: date-time */
            date?: string | null;
            note?: string;
            /** Format: uuid */
            document?: string | null;
        };
        RestAuthDetail: {
            readonly detail: string;
        };
        /**
         * @description * `system` - System
         *     * `user` - User
         *     * `assistant` - Assistant
         * @enum {string}
         */
        RoleEnum: "system" | "user" | "assistant";
        SocialLogin: {
            access_token?: string;
            code?: string;
            id_token?: string;
        };
        SocialLoginRequest: {
            access_token?: string;
            code?: string;
            id_token?: string;
        };
        /**
         * @description * `Tiếp nhận` - Intake
         *     * `Phân loại & Đăng ký` - Classification And Registration
         *     * `Phân phối` - Distribution
         *     * `Xử lý chuyên môn` - Specialized Processing
         *     * `Phê duyệt` - Approval
         *     * `Phát hành phản hồi` - Feedback Distribution
         * @enum {string}
         */
        StageEnum: "Tiếp nhận" | "Phân loại & Đăng ký" | "Phân phối" | "Xử lý chuyên môn" | "Phê duyệt" | "Phát hành phản hồi";
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        User: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Name of User */
            name?: string;
            /** Format: uri */
            readonly url: string;
        };
        /** @description User model w/o password */
        UserDetails: {
            /** ID */
            readonly pk: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            readonly first_name: string;
            readonly last_name: string;
        };
        /** @description User model w/o password */
        UserDetailsRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
        };
        UserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Name of User */
            name?: string;
        };
        WorkflowDocument: {
            /** Format: uuid */
            readonly id: string;
            suggested_reviewer?: string | null;
            suggested_dept?: string | null;
            entities?: string[];
            risk_flags?: string[];
            related_docs?: string[];
            readonly attachments: components["schemas"]["WorkflowDocumentAttachment"][];
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title?: string;
            code?: string;
            sender?: string;
            /** Format: date */
            received_date?: string | null;
            summary?: string;
            confidentiality?: components["schemas"]["ConfidentialityEnum"];
            department?: components["schemas"]["DepartmentEnum"];
            document_type?: components["schemas"]["DocumentTypeEnum"];
            status?: components["schemas"]["WorkflowDocumentStatusEnum"];
            /** Format: double */
            ai_confidence?: number | null;
            subject?: string;
            /** Format: date */
            deadline?: string | null;
            user: number;
        };
        WorkflowDocumentAttachment: {
            /** Format: uuid */
            readonly id: string;
            readonly file_size_mb: string;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            /** Format: uri */
            file: string;
            upload_file_id?: string;
            file_name?: string;
            /** Format: uuid */
            document: string;
        };
        /**
         * @description * `NEW` - Mới
         *     * `IN_PROGRESS` - Đang xử lý
         *     * `PENDING_COORDINATION` - Chờ phối hợp
         *     * `PENDING_APPROVAL` - Chờ phê duyệt
         *     * `OVERDUE` - Quá hạn
         *     * `COMPLETED` - Hoàn tất
         * @enum {string}
         */
        WorkflowDocumentStatusEnum: "NEW" | "IN_PROGRESS" | "PENDING_COORDINATION" | "PENDING_APPROVAL" | "OVERDUE" | "COMPLETED";
        WorkflowDocumentUploadInputRequest: {
            /** Format: binary */
            file: string;
        };
        WorkflowStep: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            stage?: components["schemas"]["StageEnum"];
            department: components["schemas"]["DepartmentEnum"];
            assignee: string;
            status: components["schemas"]["WorkflowStepStatusEnum"];
            /** Format: date-time */
            date?: string | null;
            note?: string;
            /** Format: uuid */
            document?: string | null;
        };
        WorkflowStepRequest: {
            stage?: components["schemas"]["StageEnum"];
            department: components["schemas"]["DepartmentEnum"];
            assignee: string;
            status: components["schemas"]["WorkflowStepStatusEnum"];
            /** Format: date-time */
            date?: string | null;
            note?: string;
            /** Format: uuid */
            document?: string | null;
        };
        /**
         * @description * `completed` - Completed
         *     * `current` - Current
         *     * `pending` - Pending
         * @enum {string}
         */
        WorkflowStepStatusEnum: "completed" | "current" | "pending";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AuthTokenRequest"];
                "multipart/form-data": components["schemas"]["AuthTokenRequest"];
                "application/json": components["schemas"]["AuthTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
        };
    };
    auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SocialLoginRequest"];
                "multipart/form-data": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialLogin"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWT"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    auth_user_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDetailsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserDetailsRequest"];
                "multipart/form-data": components["schemas"]["UserDetailsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    auth_user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserDetailsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDetailsRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserDetailsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    chats_conversations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationList"];
                };
            };
        };
    };
    chats_conversations_chat_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageChatRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MessageChatRequest"];
                "multipart/form-data": components["schemas"]["MessageChatRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    chats_conversations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
        };
    };
    chats_conversations_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConversationCreateRequest"];
                "multipart/form-data": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationCreate"];
                };
            };
        };
    };
    chats_conversations_last_7_days_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationList"];
                };
            };
        };
    };
    chats_conversations_today_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConversationList"];
                };
            };
        };
    };
    documents_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowDocumentList"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDocument"];
                };
            };
        };
    };
    documents_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["WorkflowDocumentUploadInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkflowDocumentUploadInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    orgs_agencies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAgencyList"];
                };
            };
        };
    };
    orgs_agencies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AgencyRequest"];
                "multipart/form-data": components["schemas"]["AgencyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
        };
    };
    orgs_agencies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this agency. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
        };
    };
    orgs_agencies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this agency. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AgencyRequest"];
                "multipart/form-data": components["schemas"]["AgencyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
        };
    };
    orgs_agencies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this agency. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orgs_agencies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this agency. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAgencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAgencyRequest"];
                "multipart/form-data": components["schemas"]["PatchedAgencyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
        };
    };
    orgs_agencies_departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this agency. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agency"];
                };
            };
        };
    };
    orgs_departments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDepartmentList"];
                };
            };
        };
    };
    orgs_departments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    orgs_departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    orgs_departments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    orgs_departments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orgs_departments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDepartmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedDepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    orgs_departments_tree_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    workflows_document_workflow_steps_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowStepList"];
                };
            };
        };
    };
    workflows_workflow_steps_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkflowStepList"];
                };
            };
        };
    };
    workflows_workflow_steps_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowStepRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkflowStepRequest"];
                "multipart/form-data": components["schemas"]["WorkflowStepRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStep"];
                };
            };
        };
    };
    workflows_workflow_steps_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this workflow step. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStep"];
                };
            };
        };
    };
    workflows_workflow_steps_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this workflow step. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowStepRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkflowStepRequest"];
                "multipart/form-data": components["schemas"]["WorkflowStepRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStep"];
                };
            };
        };
    };
    workflows_workflow_steps_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this workflow step. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workflows_workflow_steps_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this workflow step. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkflowStepRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorkflowStepRequest"];
                "multipart/form-data": components["schemas"]["PatchedWorkflowStepRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStep"];
                };
            };
        };
    };
}
